pub const DIT_ROOT: &str = ".dit";
pub const BLOBS_ROOT: &str = ".dit/blobs";
pub const TREES_ROOT: &str = ".dit/trees";
pub const COMMITS_ROOT: &str = ".dit/commits";
pub const BRANCHES_ROOT: &str = ".dit/branches";
pub const STAGE_ROOT: &str = ".dit/stage";
pub const STAGE_FILE: &str = ".dit/stage/staged_files";
pub const HEAD_FILE: &str = ".dit/head";
pub const IGNORE_FILE: &str=  ".ditignore";