[package]
name = "dit_core"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.2"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
thiserror = "2.0.12"
jwalk = "0.8.1"
globmatch = "0.3.0"
once_cell = "1.21.3"
