[package]
name = "dit_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
thiserror = "2.0.12"
console = "0.16.0"
tabled = "0.20.0"
chrono = "0.4.41"
dit_core = { path = "../dit_core" }

